name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11.5'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pytest-cov httpx
    - name: Run tests
      run: |
        python -m pytest tests/test_model.py -v
        python -m pytest tests/test_integration.py -v
    - name: Check code style
      run: |
        pip install flake8
        flake8 src/

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build Docker image
      run: docker build -t don-predictor .
    - name: Test Docker image
      run: |
        docker run -d -p 8000:8000 don-predictor
        sleep 10
        curl http://localhost:8000/health 